# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imposter < Formula
  desc "Reliable, scriptable and extensible mock server for REST APIs, OpenAPI (and Swagger) specifications, Salesforce and HBase APIs."
  homepage "https://www.imposter.sh"
  version "0.11.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gatehill/imposter-cli/releases/download/v0.11.7/imposter_0.11.7_macOS_x86_64.tar.gz"
      sha256 "07f615c468bf0e3dff06472e74ae7411728aaad45b6acd94b63a0ac478358d0c"

      def install
        bin.install "imposter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gatehill/imposter-cli/releases/download/v0.11.7/imposter_0.11.7_macOS_arm64.tar.gz"
      sha256 "08920a6a26a50d234a2954b18c0bab220470dab889f91e81b3d8a8503b592e74"

      def install
        bin.install "imposter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gatehill/imposter-cli/releases/download/v0.11.7/imposter_0.11.7_Linux_armv6.tar.gz"
      sha256 "fb82e3fc53f00730a94857c9506bae49e6dc52cce60d1ba9ab085311d8c55ce8"

      def install
        bin.install "imposter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gatehill/imposter-cli/releases/download/v0.11.7/imposter_0.11.7_Linux_x86_64.tar.gz"
      sha256 "4a5bba128798a78dc31f7c42b23c9dc5378a88ca8e5c0b8a285f5129e886ca89"

      def install
        bin.install "imposter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gatehill/imposter-cli/releases/download/v0.11.7/imposter_0.11.7_Linux_arm64.tar.gz"
      sha256 "4667924565a43c8e5c1d6d20e06b0320ae5aaee782586364e66d531d6ef23838"

      def install
        bin.install "imposter"
      end
    end
  end

  def caveats; <<~EOS
    Requires Docker to be installed.
  EOS
  end
end
